USE rse_quiz;

INSERT INTO user_answers (user_name, question_id, user_answer, is_correct) VALUES

('test_user', 1, 'CO2', TRUE),
('test_user', 2, 'solaire', TRUE),
('test_user', 3, 'investissement écologique', TRUE),
('test_user', 4, 'réduire les émissions', TRUE),
('test_user', 5, 'réduire les déchets', TRUE),
('test_user', 6, 'gaz à effet de serre', TRUE),
('test_user', 7, 'perte de biodiversité', TRUE),
('test_user', 8, 'CO2', TRUE),
('test_user', 9, 'haute qualité environnementale', TRUE),
('test_user', 10, 'mesurer les émissions', TRUE),
('test_user', 11, 'qualité de vie au travail', TRUE),
('test_user', 12, 'égalité des chances', TRUE),
('test_user', 13, 'favoriser l’équité', TRUE),
('test_user', 14, 'respect du temps personnel', TRUE),
('test_user', 15, 'réduire les écarts', TRUE),
('test_user', 16, 'violence psychologique', TRUE),
('test_user', 17, 'défendre les salariés', TRUE),
('test_user', 18, 'communication entre employeurs et salariés', TRUE),
('test_user', 19, 'événement survenu pendant l’activité professionnelle', TRUE),
('test_user', 20, 'évaluer le climat social', TRUE),
('test_user', 21, 'mode de décision', TRUE),
('test_user', 22, 'piloter la stratégie responsable', TRUE),
('test_user', 23, 'communication honnête', TRUE),
('test_user', 24, 'informer les parties prenantes', TRUE),
('test_user', 25, 'respect des lois', TRUE),
('test_user', 26, 'orienter la stratégie', TRUE),
('test_user', 27, 'évaluation indépendante', TRUE),
('test_user', 28, 'encadrer les comportements', TRUE),
('test_user', 29, 'acteurs impactés par l’entreprise', TRUE),
('test_user', 30, 'mesurer les progrès', TRUE),
('test_user', 31, 'respect des valeurs', TRUE),
('test_user', 32, 'intérêt personnel contre intérêt collectif', TRUE),
('test_user', 33, 'préserver l’intégrité', TRUE),
('test_user', 34, 'communication trompeuse', TRUE),
('test_user', 35, 'agir avec respect et équité', TRUE),
('test_user', 36, 'garantir la dignité', TRUE),
('test_user', 37, 'suivi des produits', TRUE),
('test_user', 38, 'respecte les normes sociales et environnementales', TRUE),
('test_user', 39, 'respect des droits fondamentaux', TRUE),
('test_user', 40, 'équité dans les relations commerciales', TRUE),
('test_user', 41, 'économie, social, environnement', TRUE),
('test_user', 42, 'impact sur la planète', TRUE),
('test_user', 43, 'atteindre un développement durable', TRUE),
('test_user', 44, 'réduction de la consommation', TRUE),
('test_user', 45, 'maintenir les équilibres naturels  ', TRUE),
('test_user', 46, 'réutilisation des déchets', TRUE),
('test_user', 47, 'minimise son impact environnemental  ', TRUE),
('test_user', 48, 'réduire la pollution', TRUE),
('test_user', 49, 'respectueux de l’environnement', TRUE),
('test_user', 50, 'produire sans épuiser les ressources', TRUE),
('test_user', 51, 'norme RSE', TRUE),
('test_user', 52, 'entreprise à impact positif', TRUE),
('test_user', 53, 'certification écologique', TRUE),
('test_user', 54, 'commerce équitable', TRUE),
('test_user', 55, 'gestion responsable des forêts', TRUE),
('test_user', 56, 'textile biologique', TRUE),
('test_user', 57, 'agriculture biologique', TRUE),
('test_user', 58, 'produit respectueux de l’environnement', TRUE),
('test_user', 59, 'engagement responsable', TRUE),
('test_user', 60, 'management environnemental', TRUE),
('test_user', 61, 'clients, salariés, fournisseurs, société', TRUE),
('test_user', 62, 'intégrer leurs attentes', TRUE),
('test_user', 63, 'élaboration collective', TRUE),
('test_user', 64, 'influencent les pratiques', TRUE),
('test_user', 65, 'favoriser l’adhésion', TRUE),
('test_user', 66, 'veille et sensibilisation', TRUE),
('test_user', 67, 'favoriser l’ancrage local', TRUE),
('test_user', 68, 'impact global de l’entreprise', TRUE),
('test_user', 69, 'financer des projets durables', TRUE);
